### ISSUE TITLE
feat: make tsconfig configurable

### ISSUE THREAD

**Issue by icehaunter** [tsmodule/tsmodule#47]
Thanks for the great project!

This is a feature request to be able to pick a `tsconfig.json` file when running `tsmodule build`.

My project has two folders in root, `src/` and `test/`, and I want to include `test/` in typechecking with `tsc` and all other tooling, but for builds I want to include only `src/` (and `tsmodule` correctly sets `rootDir` which makes it complain that `test/` files are not in the root). I believe it's common to manage two `tsconfig.json` files to accomodate for that, but that requires build command to accept an override for the used `tsconfig.json` file.

Thanks in advance!

**Comment by icehaunter** [comment]
I've noticed that the code references `tsconfig.export.ts` but that's not mentioned in the Readme, and more importantly it doesn't get honoured when generating type declarations (https://github.com/tsmodule/tsmodule/blob/master/src/commands/build/lib/emitTsDeclarations.ts#L29)

**Comment by ctjlewis** [comment]
Sorry for not seeing this. `tsconfig.export.json` was a workaround for this problem, which only occurs for `--bundle` mode:

https://github.com/evanw/esbuild/issues/2460

The general function of this tool is that you trade away all of your freedom in TSConfig (except what's not overridden) in order to comply with the [spec](https://github.com/tsmodule/tsmodule/blob/master/src/specification/index.ts).

I think I usually just add a `tsconfig` in `test/`. I will try to add something for this.

**Comment by ctjlewis** [comment]
@icehaunter - there's a `-t, --tsconfig` flag now, also the `tsconfig.export.json` is not needed anymore and can be deleted once you upgrade.

I also added the `tests`-level tsconfig, which is how you should do it (was my fault for not putting it in the template). The output program is locked to `src/` at the TypeScript level intentionally.

**Comment by ctjlewis** [comment]
Actually, I just saw your repo, and I didn't know the compiler would let you have a second output program that included `src/*` and `test/*` - that's definitely the way to go.
